-- Chạy đoạn SQL này trong Supabase > SQL Editor

create table leaderboard (
  id bigint generated by default as identity primary key,
  name text not null,
  avatar text default '🧑‍💼',
  score integer not null,
  mode text default 'Quiz',
  created_at timestamp with time zone default now()
);

-- Cho phép đọc và ghi công khai (không cần đăng nhập)
alter table leaderboard enable row level security;

create policy "Ai cũng có thể đọc" on leaderboard
  for select using (true);

create policy "Ai cũng có thể ghi" on leaderboard
  for insert with check (true);
